In [1]:
import pandas as pd
import numpy as np
import os

In [4]:
aaa = pd.read_excel('dashboard_dt_1.xlsx',index_col=0)
aaa.head()

,0,1,대학생,대학원생,교직원,교수,일반인,test_result1,test_result2,test_result3,test_result4,test_result5,tfidf1,tfidf2,tfidf3,tfidf4,tfidf5
0,칠암 창업보육센터 입주업체를,당 센터에서는 신기술과 신제품 개발로 지역 산업의 새로운 도약을 선도할 우수한 창업...,1,1,1,1,1,1,1,1,1,1,1.0,1.0,0.0,0.0,1.0
2,예비군연대 근로장학생 모집 안 내가 좌 캠퍼스,예비군연대 근로장학생 모집 예비군연대가 좌 캠퍼스 교내 근로장학생을 모집합니다 아래...,1,0,0,0,0,1,0,0,0,0,NaN,NaN,NaN,NaN,NaN
3,지속 가능발전 목표 인식 제고를 위한 교육 개최,지속 가능발전 목표 인식 제고를 위한 교육을 다음과 같이 개최하오니 관심 있는 분들...,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN
4,안내 병역판정 검사 일자 및 장소 본인 선택 안내,병무청에서는 병역판정 검사 대상자가 편리하고 자율적으로 병역의무를 이행할 수 있도록...,1,1,1,0,0,1,1,1,0,0,NaN,NaN,NaN,NaN,NaN
5,홍보 자이언 티원 슈타인 콘서트 교직원 및 학생 할인 안내,안녕하세요 단계적 일상 회복 전환에 따른 사회적 거리두기 지침이 개편됨에 따라 주전...,1,1,1,0,0,1,1,1,0,0,NaN,NaN,NaN,NaN,NaN

In [7]:
bbb = pd.read_excel('dashboard_dt_2.xlsx',index_col=0)
bbb.head()

,0,1,대학생,대학원생,교직원,교수,일반인,review,day,department
0,단체협약 체결을 위한 교섭요구 노동조합의 확정 공고,교섭요구 노동조합의 확정 공고 노동조합 및 노동관계조정법 시행령 규정에 따라 교섭요...,0,0,1,1,0,46,2021.02.25,교무과
1,경상대 변경 통학 노선버스 운행시간,통학 노선버스 관련 운행시간 변동 사항 안내 자로 운행하는 통학 노선버스는 기존 운...,1,1,1,0,0,213,2021.03.01,학생과
2,경상대 상반기 퇴직 공무원 정부포상 추천 후보자 공개검증,상반기 퇴직 공무원 포상 추천 후보자에 대해 아래와 같이 공개검증을 실시하오니 의견...,1,1,1,1,1,130,2021.03.01,총무과
3,사회적 창업 아이디어 경진대회 참가자 모집 공고,지자체 대학 협력 기반 지역 혁신사업 경남지역 혁신 플랫폼 스마트 공동체 사업단 사...,1,1,0,0,0,165,2021.03.03,스마트공동체사업단
4,재학생 등록금 납부 안내,재학생 등록금 추가 수납 일정을 아래와 같이 알려드리니 해당 학생들께서는 등록기간 ...,1,1,0,0,0,517,2021.03.03,재무과